name: gosheno
description: An app for audio book.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.3
  persian_number_utility: ^1.1.1
  cached_network_image: ^3.2.1
  currency_text_input_formatter: ^2.1.5
  google_sign_in: ^5.3.0
  googleapis: ^8.1.0
  http: ^0.13.4
  permission_handler: ^9.2.0
  connectivity_plus: ^2.3.0
  carousel_slider: ^4.1.1
  flutter_feather_icons: ^2.0.0+1
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.0.13
  animations: ^2.0.3
  just_audio: ^0.9.21
  just_audio_background: ^0.0.1-beta.5
  device_preview: ^1.1.0
  audio_session: ^0.1.6+1
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  build_runner: ^2.1.10


flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/IRANYekan_Regular.ttf
        - asset: assets/fonts/IRANYekan_Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANYekan_Black.ttf
          weight: 900