name: gosheno
description: An app for audio book.

publish_to: 'none'

version: 0.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  persian_number_utility: ^1.1.2
  cached_network_image: ^3.2.1
  google_sign_in: ^5.4.0
  googleapis: ^9.1.0
  http: ^0.13.4
  permission_handler: ^10.0.0
  connectivity_plus: ^2.3.5
  carousel_slider: ^4.1.1
  iconify_flutter: ^0.0.4
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.0.15
  animations: ^2.0.3
  just_audio: ^0.9.27
  just_audio_background: ^0.0.1-beta.7
  audio_session: ^0.1.9
  json_annotation: ^4.6.0
  lottie: ^1.3.0
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.8.5
  uni_links: ^0.5.1
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1
  build_runner: ^2.1.11


flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/animations/

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/IRANYekan_Regular.ttf
        - asset: assets/fonts/IRANYekan_Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANYekan_Black.ttf
          weight: 900